### PR TITLE
api_key create_at and expire_at

### PR DESCRIPTION
**Pull request by hbcarlos**

### CODE REVIEW

**Comment by wolfv** [comment]
sorry, I just killed beta.mamba.pm so the tests are not working. I am bringing it up ... but it takes a little while longer :see_no_evil:

**Comment by hbcarlos** [comment]
Don't worry, I'have work on the frontend. : )

**Comment by wolfv** [comment]
Testing with server_default .. let's see!

**Comment by hbcarlos** [comment]
I have to change the `datetime` to `date`.

**Comment by wolfv** [comment]
we can also keep datetime and just put the clock to 00:00:00

**Comment by wolfv** [comment]
@hbcarlos when you make the change, can you also modify to `time_created`? because that's the word we used in that other case.

**Comment by hbcarlos** [comment]
Sure

**Comment by wolfv** [comment]
can you squash the commits regarding linting a bit? you can also squash my two commits into one. 

I'll merge, but we need to keep in mind that we're not yet enforcing the expiration date anywhere.

**Pull request closed without merging**
