### PR TITLE
server level user roles

### PR DESCRIPTION
**Pull request by btel**
implementation of the [QEP1](https://hackmd.io/brJub-gXSL6oXx7UoRqcQA) (part 1)

* empty
  - [x] can read their user data
* member
  - [x] can create normal channels
* maintainer (admin)
  - [x] all above and
  - [x] can assign member role to users
  - [x] can read/modify all users’ data
  - [x] can create mirror and proxy channels
  - [x] has access to all channels (including all private channels)
* owner (super-admin)
   - [x] all above and
   - [x] can assign maintainer role to users

### CODE REVIEW

**Comment by wolfv** [comment]
I think it would be cool to have a qep folder and add the document there for eternity :)

**Comment by wolfv** [comment]
Or copy it into this PR as eternal reference

**Comment by btel** [comment]
@wolfv good to merge, I will handle the config stuff in my next PR

**Comment by wolfv** [comment]
awesome

**Pull request merged**
