### PR TITLE
Add performance-oriented dependencies

### PR DESCRIPTION
**Pull request by ivergara**
`uvicorn` can use performance oriented implementations of the event loop (uvloop) and http parsing (httptools) if they're present. This Pr adds those into the dependencies.

### CODE REVIEW

**Comment by janjagusch** [comment]
@ivergara, can you please rebase with the latest commit on main?

**Comment by janjagusch** [comment]
@ivergara, the diff still looks off. Can you try merging the latest commit on main into your branch, please?

**Comment by ivergara** [comment]
Sorry, I did somehow botch the rebase.

**Review by janjagusch — CHANGES_REQUESTED** [review]
I'm unsure if we want the two packages to be part of `install_requires`. This would imply that you must have these packages installed. There might be some use cases where this is not possible. I'm fine with adding it to the `environment.yml`, though.

What do you think?

**Comment by ivergara** [comment]
Adding it to the `environment.yml` makes little sense in my opinion. That'd only affect a local development deployment.

I do agree that having them by default might be controversial. I deemed it as a safe operation. One place it'd blow up is isntalling quetz in windows.

I'm fine with closing this.

**Pull request closed without merging**
