### PR TITLE
Make GCS bucket location configurable

### LINKED ISSUE #511: Allow configuring bucket location with GCS backend
As described in https://github.com/fsspec/gcsfs/issues/454, you weren't able to configure the default bucket location for new buckets in `gcsfs` (instead buckets were always created in the US). Hence, the same currently applies to creating new Conda channels, which will be located in the US as well. This causes quite a bit of latency and unnecessary network traffic for us, as most of our users are located in the EU. 

With https://github.com/fsspec/gcsfs/releases/tag/2022.3.0 you are now able to configure the bucket location, as described in https://github.com/fsspec/gcsfs/pull/455. We should pass this new interface on to quetz and allow defining the bucket location for new channels through the config.

I can take this on.

### PR DESCRIPTION
**Pull request by janjagusch**
Closes #511

### CODE REVIEW

**Comment by janjagusch** [comment]
Linting error will disappear after https://github.com/mamba-org/quetz/pull/513 is merged.

**Comment by janjagusch** [comment]
I'm not entirely sure what to do about the failing unit tests:

```
authlib.integrations.base_client.errors.MismatchingStateError: mismatching_state: CSRF Warning! State not equal in request and response.
2022-04-05T16:45:36.8956085Z quetz/tests/authentification/test_oauth.py::test_config_create_user_with_role_in_different_provider[jupyter_response-user_roles0-None] FAILED [ 94%]
```

But this seems to affect multiple PRs and is probably not related to my changes.

**Comment by janjagusch** [comment]
> I'm not entirely sure what to do about the failing unit tests:
> 
> ```
> authlib.integrations.base_client.errors.MismatchingStateError: mismatching_state: CSRF Warning! State not equal in request and response.
> 2022-04-05T16:45:36.8956085Z quetz/tests/authentification/test_oauth.py::test_config_create_user_with_role_in_different_provider[jupyter_response-user_roles0-None] FAILED [ 94%]
> ```
> 
> But this seems to affect multiple PRs and is probably not related to my changes.
> 
> Seems to be related to authlib: [lepture/authlib#376](https://github.com/lepture/authlib/issues/376)

Also fixed in #513

**Comment by wolfv** [comment]
Thanks, this looks good to me!

**Comment by wolfv** [comment]
I just rebased to see if tests are passing.

**Comment by janjagusch** [comment]
Thanks for merging this so quickly, @wolfv! Would it be too much to ask for a new Quetz release, so we try out this feature? 👼

**Pull request merged**
