### PR TITLE
Consider packages.conda for index update and channel mirroring

### LINKED ISSUE #599: Support .conda package format
Currently Quetz does not support the .conda package.

What is the .conda file format:
https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/packages.html#conda-file-format

conda-forge announced in November of 22' that .conda build infrastructure was ready to ship.
https://conda-forge.org/docs/orga/minutes/2022-11-16.html#

conda-forge has now started to ship some packages only in the .conda format and quetz is unable to mirror them:
https://anaconda.org/conda-forge/conda-libmamba-solver/files

Output below of the files that were mirrored by quetz v0.5.0

```
user@25607cde82fb:/tmp/test_quetz/channels/conda-forge-slim$ find . | more
.
./channeldata.json.bz2
./channeldata.json.gz
./channeldata.json
./index.html.bz2
./index.html.gz
./index.html
./noarch
./noarch/index.html.bz2
./noarch/index.html.gz
./noarch/index.html
./noarch/repodata.json
./noarch/repodata.json.bz2
./noarch/repodata.json.gz
./noarch/conda-libmamba-solver-22.3.0-pyhd8ed1ab_0.tar.bz2
./noarch/conda-libmamba-solver-22.3.1-pyhd8ed1ab_0.tar.bz2
./noarch/conda-libmamba-solver-22.6.0-pyhd8ed1ab_0.tar.bz2
./noarch/conda-libmamba-solver-22.8.1-pyhd8ed1ab_0.tar.bz2
```

### PR DESCRIPTION
**Pull request by YYYasin19**
As reported in #599: The current implementation neglects packages that are under `packages.conda` in the `repodata.json` files.
This PR should close #599; I hope I haven't missed any other places.

There's one reference to `utils/repodata_compare.py` but that file seems to be unused right now.

### CODE REVIEW

**Review by janjagusch — COMMENTED** [review]
Nice! What would be a good way to test this?

**Comment by janjagusch** [comment]
@YYYasin19, can you please rebase with the latest commit on main?

**Comment by YYYasin19** [comment]
> Nice! What would be a good way to test this?

I'll look into how the current tests are working and implement some additional ones for .conda packages.

**Review by AndreasAlbertQC — APPROVED** [review]

**Comment by wolfv** [comment]
Thank you @YYYasin19!

**Pull request merged**
