### PR TITLE
implement synchronisation of mirror channels

### PR DESCRIPTION
**Pull request by btel**
This PR implement a simple scheme for synchronization of mirrors.

To synchronize for each package it checks the `time_changed` attribute in the repodata, if the timestamp is later than the timestamp of the last synchronised package (from previous runs), it updates the file, otherwise it skips. If the attribute is not present (for example for anaconda server, it  forces the update).

In addition, this PR adds a new endpoint `PUT /channels/{channel_name}` (without data), which will trigger a synchronisation run (as a background task). Note that synchronisation is not triggered automatically.

### CODE REVIEW

**Comment by wolfv** [comment]
For anaconda servers (or others that do not implement the time_changed attribute) we could also compare the tuple `(full_package_name, SHA256 sum)`. For example `(xtensor-0.21.5-h123323.tar.bz2, 123123)`. Is this also implemented in this PR?

**Comment by btel** [comment]
yes, this could work. However, we would have to compare the tuple against quetz database for each package. Perhaps we could do this in a separate PR?

**Comment by wolfv** [comment]
we could also compare it against the latest repodata from quetz vs. anaconda

**Comment by btel** [comment]
that's right. should we try it in the next PR?

**Comment by wolfv** [comment]
yep!

**Pull request merged**
